### ISSUE TITLE
Add get notified SMS html

### ISSUE THREAD

**Issue by zoushilu31** [yalitzab/air-hiker#11]
![Screen Shot 2020-09-19 at 4 42 22 PM](https://user-images.githubusercontent.com/68711499/93691223-34bc9000-fa97-11ea-97d1-c722c126aa04.png)

**Comment by yalitzab** [comment]
That looks cool. I worked on it too. I came up with this. It needs
improvement.
[image: image.png]

**Comment by zoushilu31** [comment]
I was just testing it out to see how it would look like. I'm not able to view the image file in your comment :(
